####################################################################
#  strategy_core make include file.                                #
####################################################################

SHELL       = /bin/sh
MAKE        = make
PYTHON      = python
FORTRAN     = gfortran
 
CC          = gcc
CFLAGS      = -O3
CXX         = g++
CXXFLAGS    = $(CFLAGS)
LD          = $(CXX)
ARCH        = ar
ARCHFLAGS   = crs

BLASLIB     = -lblas
LAPACKLIB   = -llapack
TMGLIB      = -ltmglib
LAPACKELIB  = -llapacke
FORTRANLIB  = -lgfortran
